name: Build Image
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: leptos-base
  MAJOR_VERSION: 10
  DEFAULT_TAG: ${{ github.ref_name }}
  IMAGE_FULL: ghcr.io/${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - name: "Check for updates"
        if: ${{ github.event_name == 'schedule' }}  # Only run if triggered by schedule
        run: |
          upd=0
          podman run --quiet --rm ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }} dnf check-update || upd=$?

          echo "upd=${upd}" >> "$GITHUB_ENV"
          echo "Exit code from dnf check-update: '${upd}'"

      - name: "Setup"
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        shell: "bash"
        run: |
            echo "DATE=$(date -u +%Y%m%d)" >> "$GITHUB_ENV"

      - name: "Build and Rechunk with Chunkah"
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        uses: redhat-actions/buildah-build@v3.1.0
        with:
          containerfiles: "/build/Containerfile"
          oci: true
          tags: ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}
          extra-args: |
            --cap-add=all
            --device=/dev/fuse
            --skip-unused-stages=false
            --security-opt=label=disable
            -v ${{ github.workspace }}:/run/src

      - name: "GHCR Login"
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        uses: redhat-actions/podman-login@v2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Push image"
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        uses: redhat-actions/push-to-registry@v3.0.0
        id: "push"
        with:
          tags: ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}
          extra-args: |
            --compression-format=zstd:chunked
            --compression-level=3
            --force-compression

#      - name: "Install Cosign"
#        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
#        uses: sigstore/cosign-installer@v4.1.2
#
#      - name: "Sign image"
#        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
#        shell: "bash"
#        env:
#          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
#          DIGEST: ${{ steps.push.outputs.digest }}
#          IMG: ${{ env.IMAGE_FULL }}
#        run: |
#          set -euo pipefail
#          cosign sign --yes \
#            --new-bundle-format=false \
#            --use-signing-config=false \
#            --key env://COSIGN_PRIVATE_KEY \
#            "${IMG}@${DIGEST}"
